### PR TITLE
Correctly set ValueType to Counter or Gauge

### LINKED ISSUE #7: Exporter does not correctly set Counter or Gauge ValueType
The exporter currently always sets ValueType to Counter, even when the metric is in fact a Gauge.

See https://github.com/orijtech/prometheus-go-metrics-exporter/blob/master/prometheus.go#L315 (also L318) - should be `derivedPrometheusType` instead of `prometheus.CounterValue`

### PR DESCRIPTION
**Pull request by james-bebbington**
Fixes https://github.com/orijtech/prometheus-go-metrics-exporter/issues/7

### CODE REVIEW

**Review by odeke-em — APPROVED** [review]
Thank you for this change @james-bebbington and great catching you here, formally.

I have to jog my memory on why I didn’t use the derived type as it has been almost 2 years since I wrote that code, but the use of derived type LGTM!

**Comment by james-bebbington** [comment]
> Thank you for this change @james-bebbington and great catching you here, formally.
> 
> I have to jog my memory on why I didn’t use the derived type as it has been almost 2 years since I wrote that code, but the use of derived type LGTM!

No worries, @bogdandrutu was actually the one that noticed it. Thanks for the quick merge! Could you please tag this for release as well so we can update Open Telemetry Collector to use the latest version?

**Comment by odeke-em** [comment]
Awesome, thank you both @james-bebbington and @bogdandrutu. I've cut the release v0.0.5, done https://github.com/orijtech/prometheus-go-metrics-exporter/releases/tag/v0.0.5.

**Comment by james-bebbington** [comment]
Thanks!

**Pull request merged**
